kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - tag
    - pull_request

steps:
  - name: fmt
    image: golang:1.17-bullseye
    commands:
      - test -z $(go fmt ./...)
  - name: build
    image: golang:1.17-bullseye
    commands:
      - go build .

---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - tag

depends_on:
  - build

steps:
  - name: vet
    image: golang:1.17-bullseye
    commands:
      - go vet -v ./...
  - name: test
    image: golang:1.17-bullseye
    commands:
      - apt-get update
      - apt install youtube-dl -y
      - go test -v ./...